// Command gen-configurator bakes the live CLI schema into the self-contained
// configuration builder page. It reads tools/configurator.template.html, replaces
// the __CXOO_SCHEMA__ placeholder with the JSON from cli.BuildSchema(), and writes
// tools/configurator.html. CI regenerates and diffs (see .github/workflows/ci.yml),
// so the builder can never drift from the real flags.
//
// Usage: go run ./hack/gen-configurator   (from the repo root)
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/cx-michael-pogrebisky/cx-onprem-orchestrator/internal/cli"
)

const (
	templatePath = "tools/configurator.template.html"
	outputPath   = "tools/configurator.html"
	placeholder  = "__CXOO_SCHEMA__"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-configurator: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	tmpl, err := os.ReadFile(templatePath)
	if err != nil {
		return err
	}
	if !strings.Contains(string(tmpl), placeholder) {
		return fmt.Errorf("%s does not contain placeholder %s", templatePath, placeholder)
	}

	s := cli.BuildSchema()
	// Blank the version so the generated page is byte-stable across releases
	// (dev "0.0.0-dev" vs a tag) — keeps the CI drift guard deterministic.
	s.Version = ""

	// Default Marshal escapes <, >, & to \uXXXX, which is required to embed the
	// JSON safely inside a <script> element (no stray "</script>"/"<!--").
	b, err := json.Marshal(s)
	if err != nil {
		return err
	}

	out := strings.Replace(string(tmpl), placeholder, string(b), 1)
	header := "<!-- GENERATED by hack/gen-configurator from the live CLI schema. Do not edit by hand;\n" +
		"     edit tools/configurator.template.html and run: go run ./hack/gen-configurator -->\n"
	out = strings.Replace(out, "<!doctype html>\n", "<!doctype html>\n"+header, 1)

	if err := os.WriteFile(outputPath, []byte(out), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d flags, %d engines)\n", outputPath, len(s.Flags), len(s.Engines))
	return nil
}
