// Behaviour tests for the configuration builder (tools/configurator.html).
//
// These run the page's real builder logic under Node (V8 — the Chrome/Edge engine)
// with a minimal DOM stub, so they verify the generated configs without a browser.
// For real cross-engine coverage, tools/run-browser-tests.sh additionally drives the
// in-page #selftest under headless Chrome (Blink) and Firefox (Gecko).
//
//   node --test tools/configurator.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const htmlPath = path.join(here, "configurator.html");
const html = fs.readFileSync(htmlPath, "utf8");

/* ---- load the page's script into a stubbed DOM ---- */
function load() {
  const jsonM = html.match(/<script id="cxoo-schema" type="application\/json">([\s\S]*?)<\/script>/);
  assert.ok(jsonM, "schema script present");
  const mainM = html.match(/<script>\s*\n?"use strict";([\s\S]*?)<\/script>\s*<\/body>/);
  assert.ok(mainM, "main script present");

  function makeEl() {
    return {
      nodeType: 1, _kids: [], textContent: "", _innerHTML: "", className: "", value: "", checked: false, disabled: false, style: {},
      get innerHTML() { return this._innerHTML; },
      set innerHTML(v) { this._innerHTML = v; if (v === "") this._kids = []; },
      classList: { _s: new Set(), add(x){this._s.add(x);}, remove(x){this._s.delete(x);},
        toggle(x,f){ if(f===undefined)f=!this._s.has(x); f?this._s.add(x):this._s.delete(x); }, contains(x){return this._s.has(x);} },
      setAttribute(){}, removeAttribute(){}, remove(){}, focus(){}, select(){}, appendChild(c){this._kids.push(c);},
      append(...k){ this._kids.push(...k); },
      set onclick(_f){}, set onchange(_f){}, set oninput(_f){},
    };
  }
  const byId = {};
  const getEl = (id) => (byId[id] ||= makeEl());
  byId["cxoo-schema"] = makeEl(); byId["cxoo-schema"].textContent = jsonM[1];

  const document = { getElementById: getEl, createElement: () => makeEl(),
    createTextNode: (t) => ({ nodeType: 3, textContent: String(t) }), execCommand: () => true, body: makeEl() };
  const navigator = { clipboard: { writeText: async () => {} } };
  const ctx = { document, navigator, Blob: function(){}, URL: { createObjectURL: () => "blob:x" }, setTimeout, console, JSON };
  ctx.window = ctx; ctx.window.isSecureContext = false;
  vm.createContext(ctx);
  let body = '"use strict";' + mainM[1];
  body += "\nglobalThis.__state=state; globalThis.__render=render; globalThis.__out=()=>document.getElementById('output').textContent; globalThis.__notes=()=>document.getElementById('notes')._kids.map(k=>k.textContent||k.innerHTML||'').join(' | ');";
  vm.runInContext(body, ctx);
  return ctx;
}

function fresh() {
  const ctx = load();
  const S = ctx.__state;
  Object.assign(S, {
    target:"local", os:"linux", runtime:"docker",
    scanners:{sast:true,sca:true,kics:true,secrets:true,containers:true},
    source:"", projectName:"", branch:"",
    thresholds:[{engine:"sast",sev:"critical",limit:"1"},{engine:"sca",sev:"high",limit:"5"}],
    filters:{}, reportFormats:{json:true,sarif:true}, outputPath:"reports", outputName:"",
    parallel:"8", failFast:false, timeout:"", onMissing:"", conflict:"", async:false, ignoreOnExit:"",
    auth:"apikey", authEnv:{apikey:"CX1_APIKEY",clientId:"",clientSecretEnv:"CX_CLIENT_SECRET",baseUri:"",baseAuthUri:"",tenant:""},
    sast:{server:"",userEnv:"CXSAST_USERNAME",passEnv:"CXSAST_PASSWORD",team:"CxServer/SP",java:""},
    tools:{scaResolver:"",sastPath:""}, passthrough:[],
  });
  return ctx;
}
const out = (ctx) => { ctx.__render(); return ctx.__out(); };
const notes = (ctx) => { ctx.__render(); return ctx.__notes(); };

/* ---------- structural ---------- */
test("page is generated and self-contained (schema embedded, no placeholder)", () => {
  assert.ok(!html.includes("__CXOO_SCHEMA__"), "placeholder replaced");
  assert.ok(html.includes('id="cxoo-schema"'), "schema script present");
  assert.ok(html.includes("GENERATED by hack/gen-configurator"), "generated header present");
});

test("most-used Project & team section precedes Engines", () => {
  const proj = html.indexOf("Project & team — most used");
  const eng = html.indexOf("Engines (--scanners)");
  assert.ok(proj > 0 && eng > 0 && proj < eng, "Project & team comes before Engines");
});

/* ---------- local runtimes ---------- */
test("local · linux · docker", () => {
  const o = out(fresh());
  assert.match(o, /docker run --rm -v "\$PWD":\/work -w \/work/);
  assert.match(o, /-e CX1_APIKEY/);
  assert.match(o, /ghcr\.io\/cx-michael-pogrebisky\/cx-onprem-orchestrator:fat run/);
  assert.match(o, /--threshold "sast-critical=1;sca-high=5"/);
  assert.match(o, /--scanners all/);
});

test("local · linux · podman adds SELinux :Z", () => {
  const c = fresh(); c.__state.runtime = "podman";
  const o = out(c);
  assert.match(o, /podman run --rm/);
  assert.match(o, /:\/work:Z/);
});

test("local · windows · native uses .exe and PowerShell continuations", () => {
  const c = fresh(); c.__state.os = "windows"; c.__state.runtime = "native";
  const o = out(c);
  assert.match(o, /cx-onprem-orchestrator\.exe run/);
  assert.match(o, / `/);
  assert.match(o, /\$env:/);
});

test("windows + container warns about WSL2 / Server 2016", () => {
  const c = fresh(); c.__state.os = "windows"; c.__state.runtime = "docker";
  assert.match(notes(c), /WSL2/);
});

/* ---------- CI targets ---------- */
test("GitHub Actions · linux wires secrets via env block, uploads always", () => {
  const c = fresh(); c.__state.target = "github";
  const o = out(c);
  assert.match(o, /runs-on: ubuntu-latest/);
  assert.match(o, /\$\{\{ secrets\.CX1_APIKEY \}\}/);
  assert.match(o, /if: always\(\)/);
});

test("GitHub Actions · windows uses native binary + pwsh", () => {
  const c = fresh(); c.__state.target = "github"; c.__state.os = "windows"; c.__state.runtime = "native";
  const o = out(c);
  assert.match(o, /runs-on: windows-latest/);
  assert.match(o, /shell: pwsh/);
  assert.match(o, /cx-onprem-orchestrator\.exe run/);
});

test("Jenkins emits a Groovy pipeline with credentials()", () => {
  const c = fresh(); c.__state.target = "jenkins";
  const o = out(c);
  assert.match(o, /pipeline \{/);
  assert.match(o, /credentials\(/);
});

test("Jenkins · windows uses a single-line bat step", () => {
  const c = fresh(); c.__state.target = "jenkins"; c.__state.os = "windows"; c.__state.runtime = "native";
  const o = out(c);
  assert.match(o, /agent \{ label 'windows' \}/);
  assert.match(o, /bat '/);
});

test("CodeBuild · windows forces native + warns it is a Windows container", () => {
  const c = fresh(); c.__state.target = "codebuild"; c.__state.os = "windows";
  assert.match(out(c), /cx-onprem-orchestrator\.exe/);
  assert.match(notes(c).toLowerCase(), /windows container/);
});

test("every CI target renders non-empty for linux/docker and windows/native", () => {
  const targets = Object.keys(load().window ? {} : {}); // placeholder; enumerate from schema-independent list
  const all = ["github","gitlab","azure","jenkins","bamboo","bitbucket","teamcity","buildkite","codebuild","circleci","travis","drone","semaphore","appveyor","codefresh"];
  for (const t of all) {
    const a = fresh(); a.__state.target = t; const la = out(a);
    assert.ok(la && la.length > 20, `${t} linux/docker non-empty`);
    const b = fresh(); b.__state.target = t; b.__state.os = "windows"; b.__state.runtime = "native"; const lb = out(b);
    assert.ok(lb && lb.length > 20, `${t} windows/native non-empty`);
  }
});

/* ---------- flags & safety ---------- */
test("project name and team flags appear", () => {
  const c = fresh(); c.__state.projectName = "myapp"; c.__state.sast.team = "CxServer/SP";
  const o = out(c);
  assert.match(o, /--project-name myapp/);
  assert.match(o, /--sast-team CxServer\/SP/);
});

test("client-credentials wires the secret by ENV NAME only (never a value)", () => {
  const c = fresh(); c.__state.target = "gitlab"; c.__state.auth = "client-creds";
  Object.assign(c.__state.authEnv, { clientId:"cxone-ci", clientSecretEnv:"CX_CLIENT_SECRET", baseUri:"https://x.ast.checkmarx.net", baseAuthUri:"https://x.iam.checkmarx.net", tenant:"acme" });
  const o = out(c);
  assert.match(o, /--cx-client-id cxone-ci/);
  assert.match(o, /--cx-client-secret-env CX_CLIENT_SECRET/);
  assert.ok(!/--cx-client-secret\s/.test(o), "no secret VALUE flag");
});

test("secrets-total threshold and =-bound passthrough", () => {
  const c = fresh();
  c.__state.thresholds = [{engine:"secrets-total",sev:"high",limit:"1"}];
  c.__state.passthrough = [{engine:"sast",value:"-ReportPDF=report.pdf"}];
  const o = out(c);
  assert.match(o, /--threshold (")?secrets-total=1(")?/);
  assert.match(o, /--sast-arg=-ReportPDF=report\.pdf/);
});

test("no secret VALUES ever appear in output", () => {
  for (const t of ["local","github","gitlab","jenkins","azure"]) {
    const c = fresh(); c.__state.target = t;
    assert.ok(!/eyJ|REDACTED|password=\S{6}/.test(out(c)), `${t} leaks no secret value`);
  }
});

test("selecting no engines warns that --scanners is required", () => {
  const c = fresh(); c.__state.scanners = {sast:false,sca:false,kics:false,secrets:false,containers:false};
  assert.match(notes(c).toLowerCase(), /at least one engine/);
});

test("--async with --threshold warns (incompatible)", () => {
  const c = fresh(); c.__state.async = true;
  assert.match(notes(c).toLowerCase(), /async/);
});
