// Behaviour tests for the configuration builder (tools/configurator.html).
//
// These run the page's real builder logic under Node (V8 — the Chrome/Edge engine)
// with a minimal DOM stub, so they verify the generated configs without a browser.
// For real cross-engine coverage, tools/run-browser-tests.sh additionally drives the
// in-page #selftest under headless Chrome (Blink) and Firefox (Gecko).
//
//   node --test tools/configurator.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const htmlPath = path.join(here, "configurator.html");
const html = fs.readFileSync(htmlPath, "utf8");

/* ---- load the page's script into a stubbed DOM ---- */
function load() {
  const jsonM = html.match(/<script id="cxoo-schema" type="application\/json">([\s\S]*?)<\/script>/);
  assert.ok(jsonM, "schema script present");
  const mainM = html.match(/<script>\s*\n?"use strict";([\s\S]*?)<\/script>\s*<\/body>/);
  assert.ok(mainM, "main script present");

  function makeEl() {
    return {
      nodeType: 1, _kids: [], textContent: "", _innerHTML: "", className: "", value: "", checked: false, disabled: false, style: {},
      get innerHTML() { return this._innerHTML; },
      set innerHTML(v) { this._innerHTML = v; if (v === "") this._kids = []; },
      classList: { _s: new Set(), add(x){this._s.add(x);}, remove(x){this._s.delete(x);},
        toggle(x,f){ if(f===undefined)f=!this._s.has(x); f?this._s.add(x):this._s.delete(x); }, contains(x){return this._s.has(x);} },
      setAttribute(){}, removeAttribute(){}, remove(){}, focus(){}, select(){}, appendChild(c){this._kids.push(c);},
      append(...k){ this._kids.push(...k); },
      set onclick(_f){}, set onchange(_f){}, set oninput(_f){},
    };
  }
  const byId = {};
  const getEl = (id) => (byId[id] ||= makeEl());
  byId["cxoo-schema"] = makeEl(); byId["cxoo-schema"].textContent = jsonM[1];

  const document = { getElementById: getEl, querySelector: (sel) => getEl("__sel__" + sel),
    createElement: () => makeEl(), documentElement: makeEl(),
    createTextNode: (t) => ({ nodeType: 3, textContent: String(t) }), execCommand: () => true, body: makeEl() };
  document.documentElement.setAttribute = () => {};
  const navigator = { clipboard: { writeText: async () => {} } };
  const localStorage = { _m: {}, getItem(k){ return this._m[k] ?? null; }, setItem(k, v){ this._m[k] = v; } };
  const ctx = { document, navigator, localStorage, Blob: function(){}, URL: { createObjectURL: () => "blob:x" }, setTimeout, console, JSON };
  ctx.window = ctx; ctx.window.isSecureContext = false;
  vm.createContext(ctx);
  let body = '"use strict";' + mainM[1];
  body += "\nglobalThis.__state=state; globalThis.__render=render; globalThis.__out=()=>document.getElementById('output').textContent; globalThis.__notes=()=>document.getElementById('notes')._kids.map(k=>k.textContent||k.innerHTML||'').join(' | ');";
  vm.runInContext(body, ctx);
  return ctx;
}

function fresh() {
  const ctx = load();
  const S = ctx.__state;
  Object.assign(S, {
    target:"local", os:"linux", runtime:"docker",
    scanners:{sast:true,sca:true,kics:true,secrets:true,containers:true},
    source:"", projectName:"", sastProjectName:"", cxProjectName:"", branch:"",
    thresholds:[{engine:"sast",sev:"critical",limit:"1"},{engine:"sca",sev:"high",limit:"5"}],
    filters:{}, outputPath:"", outputName:"",
    parallel:"8", failFast:false, timeout:"", onMissing:"", conflict:"", async:false, ignoreOnExit:"",
    auth:"apikey", authEnv:{apikey:"CX1_APIKEY",clientId:"",clientSecretEnv:"CX_CLIENT_SECRET",baseUri:"",baseAuthUri:"",tenant:""},
    sast:{server:"",user:"",userEnv:"CXSAST_USERNAME",passEnv:"CXSAST_PASSWORD",team:"CxServer",java:""},
    tools:{scaResolver:"",sastPath:""}, passthrough:[],
  });
  // engineFormats is seeded from the schema by the page itself; don't override it.
  return ctx;
}
const out = (ctx) => { ctx.__render(); return ctx.__out(); };
const notes = (ctx) => { ctx.__render(); return ctx.__notes(); };

/* ---------- structural ---------- */
test("page is generated and self-contained (schema embedded, no placeholder)", () => {
  assert.ok(!html.includes("__CXOO_SCHEMA__"), "placeholder replaced");
  assert.ok(html.includes('id="cxoo-schema"'), "schema script present");
  assert.ok(html.includes("GENERATED by hack/gen-configurator"), "generated header present");
});

test("Engines (--scanners) section is above Project & team", () => {
  const eng = html.indexOf("Engines (--scanners)");
  const proj = html.indexOf("Project & team — most used");
  assert.ok(eng > 0 && proj > 0 && eng < proj, "Engines comes before Project & team");
});

test("page has a theme picker (Light/Dark/System) and light-theme support", () => {
  assert.match(html, /id="theme"/, "theme select present");
  for (const v of ["system", "light", "dark"]) {
    assert.ok(html.includes(`value="${v}"`), `theme option ${v}`);
  }
  assert.match(html, /prefers-color-scheme: light/, "auto light via prefers-color-scheme");
  assert.match(html, /data-theme="light"/, "explicit light theme palette");
  assert.match(html, /localStorage.getItem\("cxoo-theme"\)/, "theme persisted/initialised");
});

test("a dedicated CxSAST connection section exposes literal server + username fields", () => {
  assert.match(html, /CxSAST connection — non-secret values/);
  assert.match(html, /CxSAST server URL \(--sast-server\)/);
  assert.match(html, /CxSAST username \(--sast-user\)/);
});

/* ---------- local runtimes ---------- */
test("local · linux · docker", () => {
  const o = out(fresh());
  assert.match(o, /docker run --rm -v "\$PWD":\/work -w \/work/);
  assert.match(o, /-e CX1_APIKEY/);
  assert.match(o, /ghcr\.io\/cx-michael-pogrebisky\/cx-onprem-orchestrator:fat run/);
  assert.match(o, /--threshold "sast-critical=1;sca-high=5"/);
  assert.match(o, /--scanners all/);
});

test("local · linux · podman adds SELinux :Z", () => {
  const c = fresh(); c.__state.runtime = "podman";
  const o = out(c);
  assert.match(o, /podman run --rm/);
  assert.match(o, /:\/work:Z/);
});

test("local · windows · native uses .exe and PowerShell continuations", () => {
  const c = fresh(); c.__state.os = "windows"; c.__state.runtime = "native";
  const o = out(c);
  assert.match(o, /cx-onprem-orchestrator\.exe run/);
  assert.match(o, / `/);
  assert.match(o, /\$env:/);
});

test("windows + container warns about WSL2 / Server 2016", () => {
  const c = fresh(); c.__state.os = "windows"; c.__state.runtime = "docker";
  assert.match(notes(c), /WSL2/);
});

/* ---------- CI targets ---------- */
test("GitHub Actions · linux wires secrets via env block, uploads always", () => {
  const c = fresh(); c.__state.target = "github";
  const o = out(c);
  assert.match(o, /runs-on: ubuntu-latest/);
  assert.match(o, /\$\{\{ secrets\.CX1_APIKEY \}\}/);
  assert.match(o, /if: always\(\)/);
});

test("GitHub Actions · windows uses native binary + pwsh", () => {
  const c = fresh(); c.__state.target = "github"; c.__state.os = "windows"; c.__state.runtime = "native";
  const o = out(c);
  assert.match(o, /runs-on: windows-latest/);
  assert.match(o, /shell: pwsh/);
  assert.match(o, /cx-onprem-orchestrator\.exe run/);
});

test("Jenkins emits a Groovy pipeline with credentials()", () => {
  const c = fresh(); c.__state.target = "jenkins";
  const o = out(c);
  assert.match(o, /pipeline \{/);
  assert.match(o, /credentials\(/);
});

test("Jenkins · windows uses a single-line bat step", () => {
  const c = fresh(); c.__state.target = "jenkins"; c.__state.os = "windows"; c.__state.runtime = "native";
  const o = out(c);
  assert.match(o, /agent \{ label 'windows' \}/);
  assert.match(o, /bat '/);
});

test("CodeBuild · windows forces native + warns it is a Windows container", () => {
  const c = fresh(); c.__state.target = "codebuild"; c.__state.os = "windows";
  assert.match(out(c), /cx-onprem-orchestrator\.exe/);
  assert.match(notes(c).toLowerCase(), /windows container/);
});

test("every CI target renders non-empty for linux/docker and windows/native", () => {
  const targets = Object.keys(load().window ? {} : {}); // placeholder; enumerate from schema-independent list
  const all = ["github","gitlab","azure","jenkins","bamboo","bitbucket","teamcity","buildkite","codebuild","circleci","travis","drone","semaphore","appveyor","codefresh"];
  for (const t of all) {
    const a = fresh(); a.__state.target = t; const la = out(a);
    assert.ok(la && la.length > 20, `${t} linux/docker non-empty`);
    const b = fresh(); b.__state.target = t; b.__state.os = "windows"; b.__state.runtime = "native"; const lb = out(b);
    assert.ok(lb && lb.length > 20, `${t} windows/native non-empty`);
  }
});

/* ---------- flags & safety ---------- */
test("project name and team flags appear", () => {
  const c = fresh(); c.__state.projectName = "myapp"; c.__state.sast.team = "CxServer/SP";
  const o = out(c);
  assert.match(o, /--project-name myapp/);
  assert.match(o, /--sast-team CxServer\/SP/);
});

test("default CxSAST team is CxServer", () => {
  assert.match(out(fresh()), /--sast-team CxServer\b/);
});

test("separate CxSAST and Cx1 project names", () => {
  const c = fresh();
  c.__state.projectName = "base"; c.__state.sastProjectName = "sastproj"; c.__state.cxProjectName = "cxproj";
  const o = out(c);
  assert.match(o, /--project-name base/);
  assert.match(o, /--sast-project-name sastproj/);
  assert.match(o, /--cx-project-name cxproj/);
});

test("per-scanner report formats: SCA json-only, no global --report-formats", () => {
  const c = fresh(); c.__state.engineFormats.sca = { json: true };
  const o = out(c);
  assert.match(o, /--sca-report-formats json/);
  assert.ok(!/--report-formats\s/.test(o), "no global --report-formats");
});

test("per-scanner report formats: SAST shows only xml/pdf/csv/rtf and adds pdf", () => {
  const c = fresh();
  // SAST never offers json/sarif — its schema-declared set is xml/pdf/csv/rtf.
  const fmts = c.__state.engineFormats.sast;
  for (const f of Object.keys(fmts)) assert.ok(["xml","pdf","csv","rtf"].includes(f), `SAST format ${f} valid`);
  c.__state.engineFormats.sast = { xml: true, pdf: true };
  assert.match(out(c), /--sast-report-formats (xml,pdf|pdf,xml)/);
});

test("default report formats emit no per-engine flags (defaults are implicit)", () => {
  const o = out(fresh());
  for (const e of ["sast","sca","kics","secrets","containers"]) {
    assert.ok(!o.includes(`--${e}-report-formats`), `${e} uses default (no flag)`);
  }
});

test("client-credentials wires the secret by ENV NAME only (never a value)", () => {
  const c = fresh(); c.__state.target = "gitlab"; c.__state.auth = "client-creds";
  Object.assign(c.__state.authEnv, { clientId:"cxone-ci", clientSecretEnv:"CX_CLIENT_SECRET", baseUri:"https://x.ast.checkmarx.net", baseAuthUri:"https://x.iam.checkmarx.net", tenant:"acme" });
  const o = out(c);
  assert.match(o, /--cx-client-id cxone-ci/);
  assert.match(o, /--cx-client-secret-env CX_CLIENT_SECRET/);
  assert.ok(!/--cx-client-secret\s/.test(o), "no secret VALUE flag");
});

test("secrets-total threshold and =-bound passthrough", () => {
  const c = fresh();
  c.__state.thresholds = [{engine:"secrets-total",sev:"high",limit:"1"}];
  c.__state.passthrough = [{engine:"sast",value:"-ReportPDF=report.pdf"}];
  const o = out(c);
  assert.match(o, /--threshold (")?secrets-total=1(")?/);
  assert.match(o, /--sast-arg=-ReportPDF=report\.pdf/);
});

test("CxSAST username goes on argv; password stays env-only", () => {
  const c = fresh(); c.__state.sast.user = "admin";
  const o = out(c);
  assert.match(o, /--sast-user admin/);
  assert.ok(!o.includes("CXSAST_USERNAME"), "username not wired as env when passed directly");
  assert.match(o, /CXSAST_PASSWORD/, "password still referenced by env name");
});

test("literal CxSAST server URL + username both emit on argv", () => {
  const c = fresh();
  c.__state.sast.server = "http://cxsast.internal";
  c.__state.sast.user = "svc-checkmarx";
  const o = out(c);
  assert.match(o, /--sast-server http:\/\/cxsast\.internal/);
  assert.match(o, /--sast-user svc-checkmarx/);
});

test("blank CxSAST server falls back to the CXSAST_URL env var", () => {
  const c = fresh(); c.__state.sast.server = "";
  assert.match(out(c), /CXSAST_URL/);
});

test("real secrets are never given as direct VALUE flags (only by env name)", () => {
  // API key, client secret, CxSAST password must never appear as value-bearing flags.
  for (const t of ["local","github","gitlab","jenkins","azure"]) {
    const c = fresh(); c.__state.target = t; c.__state.auth = "client-creds";
    Object.assign(c.__state.authEnv, { clientId:"id", clientSecretEnv:"CX_CLIENT_SECRET", baseUri:"https://a", baseAuthUri:"https://b", tenant:"t" });
    const o = out(c);
    assert.ok(!/--cx-apikey(\s|=)/.test(o), `${t}: no --cx-apikey value flag`);
    assert.ok(!/--cx-client-secret(\s|=)/.test(o), `${t}: no --cx-client-secret value flag`);
    assert.ok(!/--sast-password(\s|=)/.test(o), `${t}: no --sast-password value flag`);
  }
});

test("no secret VALUES ever appear in output", () => {
  // Detect a leaked JWT-shaped token (the shape of a Cx1 API key) or a value
  // assigned to a secret flag. No real credential is embedded in this test.
  const leak = /eyJ[A-Za-z0-9._-]{12,}|--(cx-apikey|cx-client-secret|sast-password|sast-token)[= ]\S/;
  for (const t of ["local","github","gitlab","jenkins","azure"]) {
    const c = fresh(); c.__state.target = t;
    assert.ok(!leak.test(out(c)), `${t} leaks no secret value`);
  }
});

test("selecting no engines warns that --scanners is required", () => {
  const c = fresh(); c.__state.scanners = {sast:false,sca:false,kics:false,secrets:false,containers:false};
  assert.match(notes(c).toLowerCase(), /at least one engine/);
});

test("--async with --threshold warns (incompatible)", () => {
  const c = fresh(); c.__state.async = true;
  assert.match(notes(c).toLowerCase(), /async/);
});

test("incomplete OAuth2 client-credentials flags the output as INCOMPLETE", () => {
  const c = fresh();
  c.__state.auth = "client-creds";
  Object.assign(c.__state.authEnv, { clientId: "id", clientSecretEnv: "CX_CLIENT_SECRET", baseUri: "", baseAuthUri: "", tenant: "" });
  const o = out(c), n = notes(c);
  assert.match(o, /INCOMPLETE CONFIGURATION — DO NOT USE AS-IS/, "output carries an INCOMPLETE banner");
  assert.match(n, /INCOMPLETE/);
  for (const f of ["--cx-base-uri", "--cx-base-auth-uri", "--cx-tenant"]) {
    assert.ok(n.includes(f), `notes list missing ${f}`);
  }
  // Already-provided fields are NOT listed as missing.
  assert.ok(!/missing:[^.]*--cx-client-id/.test(n), "client-id was provided, not flagged missing");
});

test("complete OAuth2 client-credentials is NOT flagged", () => {
  const c = fresh();
  c.__state.auth = "client-creds";
  Object.assign(c.__state.authEnv, { clientId: "id", clientSecretEnv: "CX_CLIENT_SECRET", baseUri: "https://a", baseAuthUri: "https://b", tenant: "t" });
  const o = out(c);
  assert.ok(!o.includes("INCOMPLETE"), "complete config has no INCOMPLETE banner");
  assert.match(o, /--cx-client-id id/);
});

test("incomplete OAuth without a Cx1 engine is fine (auth unused)", () => {
  const c = fresh();
  c.__state.auth = "client-creds";
  c.__state.scanners = { sast: true, sca: false, kics: true, secrets: true, containers: false };
  Object.assign(c.__state.authEnv, { clientId: "", clientSecretEnv: "", baseUri: "", baseAuthUri: "", tenant: "" });
  assert.ok(!out(c).includes("INCOMPLETE"), "no Cx1 engine selected → OAuth completeness irrelevant");
});

test("native runtime flags each missing resource path by name", () => {
  const c = fresh();
  c.__state.runtime = "native";
  c.__state.tools = { scaResolver: "", sastPath: "", kicsQueries: "" };
  const o = out(c), n = notes(c);
  assert.match(o, /INCOMPLETE CONFIGURATION/);
  assert.ok(n.includes("--sast-path"), "names --sast-path");
  assert.ok(n.includes("--sca-resolver"), "names --sca-resolver");
  assert.ok(n.includes("--kics-queries"), "names --kics-queries");
});

test("native runtime with all paths set is complete and emits them", () => {
  const c = fresh();
  c.__state.runtime = "native";
  c.__state.tools = { scaResolver: "/o/sca/ScaResolver", sastPath: "/o/cxconsole", kicsQueries: "/o/kics/queries" };
  const o = out(c);
  assert.ok(!o.includes("INCOMPLETE"), "all native paths set → complete");
  assert.match(o, /--sca-resolver \/o\/sca\/ScaResolver/);
  assert.match(o, /--sast-path \/o\/cxconsole/);
  assert.match(o, /--kics-queries \/o\/kics\/queries/);
});

test("native check only flags engines that are selected", () => {
  const c = fresh();
  c.__state.runtime = "native";
  c.__state.scanners = { sast: false, sca: false, kics: true, secrets: true, containers: false };
  c.__state.tools = { scaResolver: "", sastPath: "", kicsQueries: "" };
  const n = notes(c);
  assert.ok(n.includes("--kics-queries"), "kics selected → flagged");
  assert.ok(!n.includes("--sast-path"), "sast not selected → not flagged");
  assert.ok(!n.includes("--sca-resolver"), "sca not selected → not flagged");
});

test("each CI wires its native branch variable when the branch field is blank", () => {
  const expect = {
    github: '--branch "$GITHUB_REF_NAME"', gitlab: '--branch "$CI_COMMIT_REF_NAME"',
    azure: '--branch "$(Build.SourceBranchName)"', jenkins: '--branch "${BRANCH_NAME:-${GIT_BRANCH#origin/}}"',
    bamboo: '--branch "$bamboo_planRepository_branchName"', bitbucket: '--branch "$BITBUCKET_BRANCH"',
    teamcity: '--branch "%teamcity.build.branch%"', buildkite: '--branch "$BUILDKITE_BRANCH"',
    circleci: '--branch "$CIRCLE_BRANCH"', travis: '--branch "$TRAVIS_BRANCH"', drone: '--branch "$DRONE_BRANCH"',
    semaphore: '--branch "$SEMAPHORE_GIT_BRANCH"', appveyor: '--branch "$APPVEYOR_REPO_BRANCH"', codefresh: '--branch "${{CF_BRANCH}}"',
  };
  for (const [t, want] of Object.entries(expect)) {
    const c = fresh(); c.__state.target = t; c.__state.branch = "";
    assert.ok(out(c).includes(want), `${t}: expected ${want}`);
  }
});

test("an explicit branch value overrides the CI native variable", () => {
  const c = fresh(); c.__state.target = "jenkins"; c.__state.branch = "release/1.2";
  const o = out(c);
  assert.match(o, /--branch release\/1\.2/);
  assert.ok(!o.includes("GIT_BRANCH"), "literal branch used, not the env expression");
});

test("Jenkins pipeline checks out the repo (source + GIT_BRANCH)", () => {
  const c = fresh(); c.__state.target = "jenkins";
  assert.match(out(c), /checkout scm/);
});

test("CodeBuild has no clean branch var, so it relies on auto-detection (no --branch)", () => {
  const c = fresh(); c.__state.target = "codebuild"; c.__state.branch = "";
  assert.ok(!out(c).includes("--branch"), "codebuild leaves branch to auto-detect");
});

test("local omits --output-path so the CLI writes reports OUTSIDE the source", () => {
  const c = fresh(); c.__state.target = "local"; c.__state.outputPath = "";
  assert.ok(!out(c).includes("--output-path"), "local relies on the CLI's outside-the-tree default");
});

test("CI defaults to a distinctive in-workspace cxoo-reports (uploadable, excluded)", () => {
  const c = fresh(); c.__state.target = "github"; c.__state.outputPath = "";
  const o = out(c);
  assert.match(o, /--output-path cxoo-reports/);
  assert.match(o, /path: cxoo-reports/);            // artifact upload references the same dir
  assert.ok(!/--output-path reports\b/.test(o), "does not use the collision-prone 'reports'");
});

test("an explicit output path is honored verbatim", () => {
  const c = fresh(); c.__state.target = "gitlab"; c.__state.outputPath = "out/scan";
  assert.match(out(c), /--output-path out\/scan/);
});

test("local target does not inject a branch variable (git auto-detect)", () => {
  const c = fresh(); c.__state.target = "local"; c.__state.branch = "";
  assert.ok(!out(c).includes("--branch"), "local relies on git");
});

test("Windows CI keeps auto-detection (no bash branch expression injected)", () => {
  const c = fresh(); c.__state.target = "github"; c.__state.os = "windows"; c.__state.runtime = "native"; c.__state.branch = "";
  assert.ok(!out(c).includes("$GITHUB_REF_NAME"), "no bash var in a pwsh command");
});

test("docker/podman runtime does NOT require native resource paths (fat image)", () => {
  for (const rt of ["docker", "podman"]) {
    const c = fresh(); c.__state.runtime = rt; c.__state.tools = { scaResolver: "", sastPath: "", kicsQueries: "" };
    assert.ok(!out(c).includes("INCOMPLETE"), `${rt}: fat image provides the tools`);
  }
});
